### ISSUE TITLE
Move all TCLAP code to a common file

### ISSUE THREAD

**Issue by brunomaga** [EPFL-SV-cpp-projects/neuro-5#114]
The three applications have the same TCLAP code .
Create a single file e.g CommandLine.cpp and CommandLine.hpp and put all TCLAP options there.
Then each all calls a function on that file e.g.
Simulation * CommandLine::parse(int argc, char * argv[], Type t)
where it populates returns a simulation with the correct values, based on the Type t (for analytical, no timestep).

**Comment by leosumi** [comment]
I just made a class to parse all the argument. All the common argument are in UserArguments and there are two class specialization for the ifs and efs to add the time step argument. I put the UserArguments in the libsimulation library for now although the best location would be in app (As always cmake is not easy).

**Comment by brunomaga** [comment]
Good stuff, I had a look. Cleaned up a bit, but it's almost as you had there. I also adapted it to the main in Implicit and Analytic solution. Did you do it alone or with @fjosephepfl  and @laurefont ? They were also doing it at same point....

**Comment by leosumi** [comment]
I should apologize to them, I did not look on github for the issue assignment.

**Comment by brunomaga** [comment]
ok np, ill give them sth else!
