### ISSUE TITLE
Add TCLAP argument for choosing which neurons should output to file

### ISSUE THREAD

**Issue by brunomaga** [EPFL-SV-cpp-projects/neuro-5#115]
When we run simulations with 10000 neurons, we dont want to have 10000 neuron_X.csv files. This should be optional. Add a CommandLine option that tells which files should be created, e.g.

check the MultiArg variable on TCLAP and create -o or --output, to be used like:
`./simulation -o 1 -o 3 -o 5 -o 10`

will create only the csv files for those neurons.  Default behavior: output only neuron_0.csv and send a warning to user.

**Comment by thaisepfl** [comment]
Hi Bruno, we've been trying to figure out how to use the command in the terminal for choosing simulation specific variables, like "output". But none seem to function, so we can't "test" our work. Could you enlighten us?

**Comment by brunomaga** [comment]
if you do `./simulation --help` it shows you details how to run.

**Comment by brunomaga** [comment]
Also, I see you added the TCLAP arguments but... you do nothing with them.
The neurons specified with `-o 1312`  should create the output file, the others should not.

I renamed `file` and `get_file` to `output_neuron_ids` and `get_output_neuron_ids` to be clearer.
