### ISSUE TITLE
Create plot for number of spikes per milisecond

### ISSUE THREAD

**Issue by brunomaga** [EPFL-SV-cpp-projects/neuro-5#163]
We need an additional file with the info of the number of spikes per millisecond. See the attachment, its a requirement. Call it `firing_rate.csv`. As an example if there are 2 spikes between `0-1` ms and 3 spikes between `1-2` ms and 4 spikes between `2-3` ms, the file should look like: 

```
t,spikes
0,2
1,3
2,4
```

![plot](https://cloud.githubusercontent.com/assets/4996797/21004170/54906f36-bd2f-11e6-9141-6cf67a2c405f.png)

**Comment by brunomaga** [comment]
Update: someone told me the plot above shows not per ms but per 5 ms... so let's just make it a (TCLAP) option to define the interval to output the firing_rate.csv file.. (default 5ms) .
Thanks @laurinekolly

**Comment by laurinekolly** [comment]
Oh, I noticed our plot had much finer lines... I'll change that :)

**Comment by brunomaga** [comment]
i already fixed by plotting more lines
